version: "3.8"

services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command:
      [
        "postgres",
        "-c",
        "log_connections=on",
        "-c",
        "log_disconnections=on",
        "-c",
        "log_destination=stderr"
      ]
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  web:
    build:
      context: .
    image: {{ cookiecutter.package_name }}/web:latest
    command: [ "./scripts/wait-for-postgres.sh", "./scripts/start-reload.sh" ]
    depends_on:
      - db
    environment:
      HOSTNAME: web
      MODULE_NAME: {{ cookiecutter.package_name }}.main
      SETTINGS_YAML_FILE: config.dev.yaml
    ports:
      - "8000:80"
      - "5678:5678" # debugpy
    volumes:
      - .:/app
