; Usage of setup.cfg is not recommended unless for very simple use cases. 
; https://docs.pytest.org/en/latest/reference/customize.html

[pytest]
env = 
    SETTINGS_YAML_FILE=config.test.yaml
asyncio_mode = auto
testpaths = src
; Apparently, gevent is enabling "flush to zero":
; https://github.com/numpy/numpy/issues/20895
; Suppress the corresponding warnings:
filterwarnings =
    ignore:The value of the smallest subnormal for <class 'numpy.float32'> type is zero.:UserWarning
    ignore:The value of the smallest subnormal for <class 'numpy.float64'> type is zero.:UserWarning
