name: test

# Run on pull requests and on the master branch itself.
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      # Checkout the code.
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo apt-get install python3-venv
          python3 -m venv .
          bin/pip install -r requirements.txt
      - name: test
        run: bin/pytest
